name: front build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front/**'
     
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: serveur-web-docker-tlegrand
      ACTOR: kiv0x

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: front
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}-front:1.0.0